CREATE DATABASE my_newdb;
CREATE USER 'iobba'@'%' IDENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON my_newdb.* TO 'iobba'@'%';  
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'iobba12345';